2020-03-17 10:28:38,451 ERROR: Exception on /login [GET] [in c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\routes.py", line 54, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-03-17 10:28:40,179 ERROR: Exception on /login [GET] [in c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\routes.py", line 54, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\templates\login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\alec\appdata\local\programs\python\python38\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-03-17 10:29:45,888 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:45]
2020-03-17 10:37:33,865 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:47]
2020-03-17 10:52:45,645 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:47]
2020-03-17 11:57:39,236 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:47]
2020-03-17 12:07:06,828 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:47]
2020-03-17 12:20:34,500 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:47]
2020-03-17 12:31:46,061 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:47]
2020-03-17 12:32:20,706 INFO: Microblog startup [in C:\Users\Alec\Documents\Development\FlaskStuff\microblog\app\__init__.py:47]
